# Wrangler configuration for email notifications worker
name = "pm-email-notifications"
main = "email-notifications.js"
compatibility_date = "2024-01-01"

# Cron trigger - runs every hour
[triggers]
crons = ["0 * * * *"]

# Environment variables (set via `wrangler secret put`)
# SUPABASE_URL
# SUPABASE_SERVICE_KEY
# RESEND_API_KEY (or SENDGRID_API_KEY)
# FROM_EMAIL
# WORKER_SECRET
