name: Code Quality Checks

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint
        continue-on-error: true
      
      - name: Annotate code linting results
        uses: ataylorme/eslint-annotate-action@v2
        if: always()
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          report-json: "eslint-report.json"
          only-pr-files: true

  typescript:
    name: TypeScript Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run TypeScript compiler
        run: npx tsc --noEmit
      
      - name: Check for type errors
        run: |
          if npx tsc --noEmit 2>&1 | grep -q "error TS"; then
            echo "TypeScript errors found!"
            exit 1
          fi
          echo "No TypeScript errors found!"

  prettier:
    name: Code Formatting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check code formatting
        run: npx prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,md}"
        continue-on-error: true

  code-quality:
    name: Code Quality Report
    runs-on: ubuntu-latest
    needs: [eslint, typescript, prettier]
    if: always()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate quality report
        run: |
          echo "# Code Quality Report" > quality-report.md
          echo "## Summary" >> quality-report.md
          echo "- ESLint: ${{ needs.eslint.result }}" >> quality-report.md
          echo "- TypeScript: ${{ needs.typescript.result }}" >> quality-report.md
          echo "- Prettier: ${{ needs.prettier.result }}" >> quality-report.md
      
      - name: Upload quality report
        uses: actions/upload-artifact@v3
        with:
          name: quality-report
          path: quality-report.md
          retention-days: 30

  dependencies:
    name: Dependency Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Run npm audit
        run: npm audit --audit-level=high
        continue-on-error: true
      
      - name: Check for outdated dependencies
        run: npm outdated || true
      
      - name: Generate dependency report
        run: |
          echo "# Dependency Report" > dependency-report.md
          echo "## Audit Results" >> dependency-report.md
          npm audit --audit-level=low >> dependency-report.md || true
          echo "" >> dependency-report.md
          echo "## Outdated Packages" >> dependency-report.md
          npm outdated >> dependency-report.md || true
      
      - name: Upload dependency report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-report
          path: dependency-report.md
          retention-days: 30
